mutations_per_generation = 8
initial_program_length = 8
max_runtime = 1024
population_size = 64
inputs =  [[1, 2, 3, 4, 5, 6, 7, 8, 9], [9, 2, 5, 3], [100, 700], [1]]
targets = [[9, 8, 7, 6, 5, 4, 3, 2, 1], [3, 5, 2, 9], [700, 100], [1]]
free_mut = true
