[package]
authors = ["SilverWingedSeraph <lfstindall@gmail.com>"]
name = "evolve-sbrain"
version = "0.1.0"
[dependencies]
random = "*"
rayon = "*"
sbrain = "*"
serde = "^1"
serde_derive = "^1"
toml = "^0.4"
